[tox]
envlist = pandas,polars,ibis
skip_missing_interpreters = true

[testenv]
package = editable
deps =
    pytest
commands =
    uv run pytest tests/test_smoke.py -v

[testenv:pandas]
deps =
    pytest
    pandas>=2.2.3

[testenv:polars]
deps =
    pytest
    polars>=1.33.0

[testenv:ibis]
deps =
    pytest
    ibis-framework[duckdb]>=9.5.0
